title: "これさえ読めばQOL爆上がり【AI、金融リテラシー、便利ツール、サービスまとめ】"
summary: "A7が現在やっていることを大公開。全てやれば、僕に追いつける。やってみて合わなかったこともレビュー。"
topics: ["AI", "金融", "便利ツール", "サービス"]
published: false
price: 980 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
